### ISSUE TITLE
Pokemon details update

### ISSUE THREAD

**Issue by kristina-grujic** [stefan096/android-pokeGo#13]
Layout list update:

1. Lista pokemona

Izbaciti health, attack i defence sa liste - prikazati samo ikonicu (ostaje ista za sad), ime i level

2. Detalji o pokemonu

Izmeniti layout tako da odgovara slici na mockup-u. Pored postojecih info, dodati i level u prikaz (moze ispod imena)

**Comment by kristina-grujic** [comment]
Zasto si zatvorio ovo?

**Comment by stefan096** [comment]
bilo kasno pa sam promasio 🗡️
